name: Test this action

on:
  push:
    paths-ignore:
      - '*.md'
  pull_request:
    paths-ignore:
      - '*.md'

jobs:
  test:
    name: ${{ matrix.platform }}
    runs-on: ${{ matrix.platform }}

    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository

    strategy:
      matrix:
        platform:
          - ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup diff-pdf
      uses: ./
      with:
        diff-pdf-version: 0.5


    - name: Echo diff-pdf
      run: diff-pdf --help
