name: Test this action

on:
  push:
    paths-ignore:
    - README.md
  pull_request:
  workflow_dispatch:

jobs:
  test:
    name: ${{ matrix.platform }}
    runs-on: ${{ matrix.platform }}

    # Run this build only on either pull request or push.
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository

    strategy:
      matrix:
        platform:
          - ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: ./
      with:
        diff-pdf-version: 0.5


    - name: Execute diff-pdf command
      run: diff-pdf --help
